// <auto-generated />
using Admissions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Admissions.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611091457_WidenProgramName")]
    partial class WidenProgramName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Admissions.Domain.Entities.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("Admissions.Domain.Entities.PriorityBreakdown", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProgramYearStatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramYearStatId", "Priority")
                        .IsUnique();

                    b.ToTable("PriorityBreakdowns");
                });

            modelBuilder.Entity("Admissions.Domain.Entities.Program", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DegreeLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FieldId");

                    b.HasIndex("UniversityId");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("Admissions.Domain.Entities.ProgramYearStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnouncedPlaces")
                        .HasColumnType("int");

                    b.Property<decimal>("AnnualFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("EnrolledCount")
                        .HasColumnType("int");

                    b.Property<int>("FirstPriorityCount")
                        .HasColumnType("int");

                    b.Property<int?>("GrantFullCount")
                        .HasColumnType("int");

                    b.Property<int?>("GrantPartialCount")
                        .HasColumnType("int");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalPriorityCount")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId", "Year")
                        .IsUnique();

                    b.ToTable("ProgramYearStats");
                });

            modelBuilder.Entity("Admissions.Domain.Entities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("Admissions.Domain.Entities.PriorityBreakdown", b =>
                {
                    b.HasOne("Admissions.Domain.Entities.ProgramYearStat", "ProgramYearStat")
                        .WithMany("PriorityBreakdowns")
                        .HasForeignKey("ProgramYearStatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramYearStat");
                });

            modelBuilder.Entity("Admissions.Domain.Entities.Program", b =>
                {
                    b.HasOne("Admissions.Domain.Entities.Field", "Field")
                        .WithMany("Programs")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Admissions.Domain.Entities.University", "University")
                        .WithMany("Programs")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Admissions.Domain.Entities.ProgramYearStat", b =>
                {
                    b.HasOne("Admissions.Domain.Entities.Program", "Program")
                        .WithMany("YearStats")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Admissions.Domain.Entities.Field", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("Admissions.Domain.Entities.Program", b =>
                {
                    b.Navigation("YearStats");
                });

            modelBuilder.Entity("Admissions.Domain.Entities.ProgramYearStat", b =>
                {
                    b.Navigation("PriorityBreakdowns");
                });

            modelBuilder.Entity("Admissions.Domain.Entities.University", b =>
                {
                    b.Navigation("Programs");
                });
#pragma warning restore 612, 618
        }
    }
}
